### ISSUE TITLE
Agregar más documentación al README.md

### ISSUE THREAD

**Issue by ragnarok22** [alexfdezsauco/Nothing.Nauta#1]
En el README.md se debería incluir, no solo como usarlo, sino también cómo instalarlo. Así, las personas que no dominen esa tecnología sepan que necesitan y como instalarlo. Además sería bueno agregarle un github action que lo compilara para Linux/Windows/Mac y sea solo agregarlo al path

**Comment by alexfdezsauco** [comment]
1) Es un proyecto open source, se aceptan pull requests, documentacion incluida ;)

2) "Los" artefactos distribuibles de este proyecto se construye en azure devops. En este caso estamos hablando de una biblioteca que se distribuye como paquete NuGet, ciertamente es cross-platform  dado que .NET lo es. Si probablemente deba incluir alguna referencia a como instalar el paquete https://www.nuget.org/packages/Nothing.Nauta/1.0.0-alpha0047.

3) Imagino que en lo que estas interesado es exactamente al command line, ocurre que es un proyecto de ejemplo, por eso estan solo los fuentes. Ese ejecutable es de hecho cross-platform tambien. Si encuentro tiempo el fin de semana, lo separo de repo, y distribuyo el ejecutable.

Repito los PR son bienvenidos :)

**Comment by ragnarok22** [comment]
Ojalá mis conocimientos llegaran ahí pues .net jamás lo he tocado, por eso me quedé un poco perdido de como instalarlo en mi máquina. De todas formas muchísimas gracias por la respuesta y la herramienta.

**Comment by alexfdezsauco** [comment]
Por aca un release, con los ejecutables como assets incluida versiones auto-contenidas. 

https://github.com/alexfdezsauco/Nothing.Nauta/releases/tag/1.0.0-alpha0063

**Comment by alexfdezsauco** [comment]
Actualizado readme, espero que sea suficiente.  Por lo que cierro el issue.
